# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationtoken',
            name='expired_on',
            field=models.DateTimeField(null=True),
        ),
    ]
