# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 07:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_auto_20170619_0305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=100)),
                ('join_date', models.DateField(default=None, null=True)),
                ('left_date', models.DateField(default=None, null=True)),
                ('grade', models.CharField(default=None, max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.TextField(default='New to iGo network')),
                ('dob', models.DateField()),
                ('status', models.CharField(default=None, max_length=50)),
                ('blood_group', models.CharField(max_length=10)),
                ('current_location', models.CharField(max_length=50)),
                ('current_address', models.TextField(default=None, max_length=150)),
                ('website', models.URLField(default='http://www.techtrendz.in')),
                ('facebook', models.CharField(default=None, max_length=100)),
                ('git', models.CharField(default=None, max_length=100)),
                ('dp', models.URLField(default='http://localhost/uploads/a1df072abf2a58cfa0bd90fce5a0b65eac9e4952e7dc8c1b1dd05c24bfdb3947/images/default.png')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
