# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 13:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_education_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PasswordRestToken',
            new_name='PasswordResetToken',
        ),
    ]
