# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_profile_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='website',
            field=models.URLField(default='http://www.techtrendz.in', null=True),
        ),
    ]
