# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20170620_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='facebook',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='git',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
