# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20170620_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='is_studying',
            field=models.BooleanField(default=False),
        ),
    ]
