# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20170622_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeds',
            name='upload_image',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='feeds',
            name='upload_location',
            field=models.CharField(default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='feeds',
            name='upload_video',
            field=models.URLField(default=None, null=True),
        ),
    ]
