# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 05:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedid', to='home.Feeds'),
        ),
    ]
